import type { Metadata } from "next";

import "./globals.css";

import SiteNavbar from '@/components/SiteNavbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SiteNavbar />

        <div className="container mt-5">
          {children}
        </div>
      </body>
    </html>
  );
}
